### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AnniGr** [mammoai/cobra-db#1]
[Suggestions.pdf](https://github.com/mammoai/cobra-db/files/10343932/Suggestions.pdf)

(rewriting same info in markdown)

Include an “Introduction” page in the toolbar above the tutorial pages.

 - Instead of “what is this?” → “what is cobra_db?”
 - maybe add “With cobra_db, you will have more control over your data enabling you to get more value from your medical imaging studies.”

## Contributing
 - Get started
   - Fix this part of the sentence: “When you’re done making changes, check that your the tests are passing”.
 - It could be good to mention the vision for the project (the goals) and how the contributors should (or should not) get in touch with you.
 - Add acknowledgements
 - Under the “code of conduct” it says `Please note that the cobra_db project is released with a Code of Conduct. By contributing to this project you agree to abide by its terms.`
   - Is it possible to enable the user to click on the Code of conduct in the sentence so they can automatically go to that page?

## In the future
 - Could be good to enable users to discuss and ask questions about the package. It
can be a useful resource for users who want to learn more about the software or
get help with using it.
 - A glossary may be necessary

**Comment by fcossio** [comment]
Hi @AnniGr, thanks for the valuable feedback. I have addressed most of the points. But I would like to ask one question.

What terms do you think should go to the glossary?

You may find the Pull Request (PR) #2 . Please review the changes there and I will update the PR accordingly.

**Comment by AnniGr** [comment]
Hi @fcossio, I was thinking of the instance names in the tutorial. For example, "SOPInstanceUID", "SeriesInstanceUID", "StudyInstanceUID", and"PatientID"

**Comment by fcossio** [comment]
I will create a new issue for the glossary
