### ISSUE TITLE
Feedback on the cobra-db documentation

### ISSUE THREAD

**Issue by AnniGr** [mammoai/cobra-db#11]
[Feedback.pdf](https://github.com/mammoai/cobra-db/files/9888159/Feedback.pdf)

**Comment by fcossio** [comment]
Thank you for the valuable feedback @AnniGr. I have incorporated your comments in the documentation 🎉 You should be able to see it [here](https://cobra-db.readthedocs.io/en/latest/tutorial.html) in a few minutes
