### ISSUE TITLE
Add ethical_approval variable to the Metadata

### ISSUE THREAD

**Issue by fcossio** [mammoai/cobra-db#16]
We would like to keep the ethical approval information correctly linked to the data in the database.
We will use an `ethical_approval` field to do this. A new collection EthicalApproval should be in place with the details.

Given that the same image might be under multiple ethical approvals, the type of the field should be `List[str]`

**Comment by Huili61** [comment]
The branch was created here: 
https://github.com/mammoai/cobra-db/tree/ethical

**Comment by Huili61** [comment]
I meet some questions:
1. Do we need to write ethical_approval ingestion functions in cobra?
No, we have other issue for that
3. How to write test functions?
solved

**Comment by Huili61** [comment]
test result
![image](https://github.com/mammoai/cobra-db/assets/113504539/e95a4463-91c3-4e44-9bfd-312897c72e49)

**Comment by Huili61** [comment]
@aa17537 Taeyang will leave some comments and Fernando will merge the branch based on the comments
